spring:
  application:
    name: clientms

  datasource:
    url: jdbc:postgresql://localhost:5432/clientdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true