spring:
  application:
    name: stockms

  datasource:
    url: jdbc:postgresql://localhost:5432/stockdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

springdoc:
  swagger-ui:
    url: /openapi.yaml