services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  orderms:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderms
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - postgres

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  postgres-data: