spring:
  application:
    name: orderms

  datasource:
    url: jdbc:postgresql://localhost:5432/orderdb
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

server:
  port: 8081